### ISSUE TITLE
把Session数据保存在Cache中?

### ISSUE THREAD

**Issue by zhangethan** [daoye/MemorySessionProvider#1]
Session丢失可能是因为应用程序池回收进程了吧? 如果Session数据丢失,Cache数据会不会也丢失?

**Comment by daoye** [comment]
Session丢失的原因是因为某个处理请求的进程被关闭或重启，因为.NET的Session默认是存储在进程中的；当然缓存在应用程序池中的数据在应用程序池回收的时候也可能会丢失，但这比缓存在进程中已经稳定太多了，毕竟Session只是用来存储临时的、易丢失的数据。
如果你要追求绝对的稳定，可以使用数据库（但这会有效率损失），或者进程外存储（Memcached等）。

nozeryu@yeah.net
 发件人： zhangethan发送时间： 2015-06-18 10:00收件人： daoye/MemorySessionProvider主题： [MemorySessionProvider] 把Session数据保存在Cache中? (#1)Session丢失可能是因为应用程序池回收进程了吧? 如果Session数据丢失,Cache数据会不会也丢失?
